package com.datamodel.anvizent.helper;

public enum MasterSchedulerConstants {
	CLIENTS_UPLOAD_GROUP,
	CLIENTS_EXECUTION_GROUP,
	SCHEDULED_PACKAGES,
	CLOUD_CLIENT_SOURCE_UPLOAD_GROUP,
	CLOUD_CLIENT_PACKAGE_IDENTIFY_GROUP_FOR_EXECUTION,
	SLAVE_HEART_BEAT_CHECKER,
	;
	
	
	
}
