<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<script src="<c:url value="/resources/js/pageScripts/common.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/ETLAdmin.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/createContextParameter.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/createDL.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/createIL.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/clientDLMapping.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/iLDLMapping.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/fileSettings.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/clientErrorLogs.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/template.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/webServiceILMapping.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/vertical.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/iLInfo.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/clientSpecificILDL.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/addWebService.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/template.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/webServiceClientMapping.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/dlKpiMapping.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/defaultQueries.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/tableScripts.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/dashBoardLayoutMaster.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/clientTableScripts.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/database.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/connector.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/contextParameters.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/clientTableScriptsMapping.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/clientTableScriptExecution.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/viewILDL.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/defaultMappingConfiguation.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/allMappingInfo.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/webServiceTemplate.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/generalSettings.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/clientConfigurationSettings.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/serverConfiguration.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/migrateTemplate.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/templateMigration.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/currencyIntegration.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/versionUpgrade.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/clientCurrencyMapping.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/internalization.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/s3BucketInfo.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/scheduleStatus.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/clientS3Mapping.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/middleLevelManager.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/hybridClientsGrouping.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/appDbVersionTableScript.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/clientsInstantScriptExecution.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/clientJobExecutionParameters.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/eltConfigTags.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/eltJobTags.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/eltMasterConfiguration.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/eltLoadParameter.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/multiClientInsertScriptsExecution.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/addBusinessCaseValidation.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/addPreloadValidation.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/dataValidationType.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/adminScripts/webServiceAuthParamsEncryption.js?${build}"/>"></script>