package com.anvizent.scheduler.constants;

public interface JobConstants {
	String PACKAGE_RUNNER_CHECK_PACKAGES_TO_UPLOAD = "PACKAGE_RUNNER_CHECK_PACKAGES_TO_UPLOAD";
	String PACKAGE_RUNNER_CHECK_PACKAGES_TO_UPLOAD_GROUP = "PACKAGE_RUNNER_CHECK_PACKAGES_TO_UPLOAD_GROUP";
}
