<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<script src="<c:url value="/resources/js/pageScripts/common.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/package.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/standardPackage.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/customPackage.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/schedule.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/scheduleResults.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/queryBuilder.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/tableBuilder.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/viewResults.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/viewIlSource.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/viewCustomPackageSource.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/derivedTable.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/easyquerybuilder.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/databaseConnection.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/crossReference.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/historicalLoad.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/webServiceConnection.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/commonUpdateFileMappingWithILTable.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/currencyLoad.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/ddLayout.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/scheduleStatus.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/packageExecution.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/scheduleJobInfo.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/apisData.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/hierarchicalData.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/validateBusinessCases.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/viewValidationScriptResults.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/validatePreload.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/aiBusinessProblem.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/aiSourceDefinition.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/aiJobsUpload.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/aiContextParameters.js?${build}"/>"></script>
<script src="<c:url value="/resources/js/pageScripts/aiModel.js?${build}"/>"></script>